# Generated by Django 4.1.5 on 2023-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('mexican', 'Mexicana'), ('healthy', 'Saudável'), ('brazilian', 'Brasileira'), ('japanese', 'Japonesa'), ('italian', 'Italiana')], default='plate', max_length=20)),
            ],
        ),
    ]
