# Generated by Django 4.1.2 on 2023-02-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('lat', models.CharField(max_length=10)),
                ('lng', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('establishment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('categories', models.CharField(max_length=255)),
                ('delivery', models.BooleanField(default=False)),
                ('activity_time', models.TimeField()),
                ('image', models.CharField(max_length=100)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('owner', 'Proprietário')], max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], max_length=15)),
                ('establishment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.establishment')),
            ],
        ),
    ]
