# Generated by Django 4.1.2 on 2023-02-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
