# Generated by Django 4.1.5 on 2023-02-23 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('plate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('delivery', models.BooleanField(default=False)),
                ('establishment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('amount', models.IntegerField(default=0)),
                ('send_time', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=100)),
                ('change', models.FloatField(default=0.0, null=True)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.address')),
                ('plate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.menu')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
