# Generated by Django 4.1.2 on 2023-02-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_menu_order_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='delivery',
        ),
    ]
