# Generated by Django 4.1.5 on 2023-02-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='establishment_id',
        ),
    ]
