# Generated by Django 4.1.2 on 2023-02-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_remove_menu_categories_remove_menu_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Entregue'), ('waiting', 'Aguardando'), ('canceled', 'Cancelado')], default='waiting', max_length=20),
        ),
    ]
