# Generated by Django 4.1.2 on 2023-02-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='order_id',
        ),
    ]
