# Generated by Django 4.1.5 on 2023-02-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_remove_menu_establishment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='establishment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.establishment'),
        ),
    ]
