# Generated by Django 4.1.5 on 2023-02-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_menu_establishment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='plate_id',
            new_name='menu_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plate_id',
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.menu')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.order')),
            ],
        ),
    ]
