# Generated by Django 4.1.2 on 2023-02-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_remove_plate_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='category',
            field=models.CharField(choices=[('plate', 'Prato'), ('drink', 'Bebida')], default='plate', max_length=20),
        ),
    ]
