# Generated by Django 4.1.5 on 2023-02-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_rename_plate_id_menu_menu_id_remove_menu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.order'),
        ),
    ]
