# Generated by Django 4.1.5 on 2023-02-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_establishment_rate'),
        ('guest', '0007_alter_plate_order_id'),
    ]

    operations = [
    ]
