# Generated by Django 4.1.2 on 2023-02-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Entregue'), ('waiting', 'Aguardando'), ('canceled', 'Cancelado'), ('in_cart', 'No carrinho')], default='waiting', max_length=20),
        ),
    ]
