# Generated by Django 4.1.2 on 2023-02-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_remove_cart_order_id_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='change',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.order')),
                ('plate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.plate')),
            ],
        ),
    ]
