# Generated by Django 4.1.5 on 2023-02-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_remove_order_amount_remove_order_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='establishment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.establishment'),
        ),
    ]
